// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Super_Shop.Models;

namespace Super_Shop.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20210929083234_FixManytomany1")]
    partial class FixManytomany1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeroTeam", b =>
                {
                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("MembersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("HeroTeam");
                });

            modelBuilder.Entity("Super_Shop.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ImageUri = "~/img/employees/eric.jfif",
                            Name = "Eric Kuijpers",
                            Role = "CEO"
                        },
                        new
                        {
                            ID = -2,
                            ImageUri = "~/img/employees/carron.jfif",
                            Name = "Carron Schilders",
                            Role = "CTO"
                        },
                        new
                        {
                            ID = -3,
                            ImageUri = "~/img/employees/stijn.jfif",
                            Name = "Stijn Smulders",
                            Role = "Service desk"
                        });
                });

            modelBuilder.Entity("Super_Shop.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUri = "~/img/iron_man.png",
                            Name = "Iron Man",
                            PowerLevel = 9001
                        },
                        new
                        {
                            Id = 2,
                            ImageUri = "~/img/kermit.png",
                            Name = "Kermit the frog",
                            PowerLevel = 5
                        },
                        new
                        {
                            Id = 3,
                            ImageUri = "~/img/batman.png",
                            Name = "Batman",
                            PowerLevel = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUri = "~/img/deadpool.png",
                            Name = "Deadpool",
                            PowerLevel = 200
                        },
                        new
                        {
                            Id = 5,
                            ImageUri = "~/img/wolverine.png",
                            Name = "Wolverine",
                            PowerLevel = 150
                        });
                });

            modelBuilder.Entity("Super_Shop.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUri = "",
                            Name = "The dream team"
                        },
                        new
                        {
                            Id = 3,
                            ImageUri = "",
                            Name = "Dharma Initiative"
                        });
                });

            modelBuilder.Entity("HeroTeam", b =>
                {
                    b.HasOne("Super_Shop.Models.Hero", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Super_Shop.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
